---
routes:
 - 2:
    - weekday-eastbound:
      - 4523
      - 172
      - 121
      - 124
      - 131
      - 142
      - 154
      - 95
      - 227
      - 244
      - 4104
    - weekday-westbound:
      - 4104
      - 227
      - 17
      - 19
      - 20
      - 38
      - 45
      - 52
      - 55
      - 75
      - 4523
    - saturday-eastbound:
      - 4523
      - 172
      - 121
      - 124
      - 131
      - 142
      - 154
      - 95
      - 227
    - saturday-westbound:
      - 227
      - 19
      - 20
      - 38
      - 45
      - 52
      - 55
      - 75
      - 4523
    - sunday-eastbound:
      - 4523
      - 172
      - 121
      - 124
      - 131
      - 142
      - 154
      - 95
      - 227
    - sunday-westbound:
      - 227
      - 19
      - 20
      - 38
      - 45
      - 52
      - 55
      - 75
      - 4523
    - state-holidays-eastbound:
      - 4523
      - 172
      - 121
      - 124
      - 131
      - 142
      - 154
      - 95
      - 227
    - state-holidays-westbound:
      - 227
      - 19
      - 20
      - 38
      - 45
      - 52
      - 55
      - 75
      - 4523
